name: parkintest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-278.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1 # O la última versión estable
  lottie: ^3.3.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.9.0
  intl: ^0.18.1
  image_picker: ^1.0.0
  firebase_storage: ^11.0.0
  http: ^1.1.0
  image: ^4.0.17
  youtube_player_flutter: 9.0.4
  flutter_inappwebview: ^6.0.0
  lucide_icons: ^0.257.0
  youtube_player_iframe: ^5.1.3
  introduction_screen: ^3.1.8
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_tts: ^3.8.5
  #para supabase
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0

  equatable: ^2.0.7
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/fonts/
    - assets/images/
    - assets/banners/
    - assets/.env

  fonts:
    - family: Bakery
      fonts:
        - asset: assets/fonts/bakery.otf
          weight: 400
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica.otf
          weight: 400
    - family: Anydore
      fonts:
        - asset: assets/fonts/anydore.otf
          weight: 400
    - family: Farewell
      fonts:
        - asset: assets/fonts/farewell.ttf
          weight: 400


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png   
  min_sdk_android: 21
  remove_alpha_ios: true 
